# Generated by Django 4.2.1 on 2023-05-13 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_username_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
