# Generated by Django 4.2.1 on 2023-05-13 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_usercustom_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
