# Generated by Django 4.2.1 on 2023-05-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_usercustom_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercustom',
            old_name='persons',
            new_name='person',
        ),
        migrations.AlterField(
            model_name='usercustom',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Administrator'),
        ),
    ]
