# Generated by Django 4.2.1 on 2023-05-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='city',
        ),
        migrations.AlterField(
            model_name='address',
            name='neighborhood',
            field=models.CharField(max_length=100, verbose_name='Neighborhood'),
        ),
        migrations.AddConstraint(
            model_name='uf',
            constraint=models.UniqueConstraint(models.F('name'), models.F('acronym'), name='unique_uf_name_acronym'),
        ),
        migrations.DeleteModel(
            name='Neighborhood',
        ),
    ]
