# Generated by Django 4.2.1 on 2023-05-31 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_remove_neighborhood_city_alter_address_neighborhood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
    ]
